export default {
  AUTH_TOKEN: 'USER_TOKEN',
  SIGN_TYPE: 'SIGNUP_VERIFICATION',
  FORGOT_TYPE: 'FORGOT_VERIFICATION',
  SELECTED_LANGUAGE: 'selectedLang',
  USER_DATA: 'USER_DATA',
  NOTIFICATION: 'NOTIFICATION_SETTINGS',
  OTP_TIMESTAMP: 'otpTimestamps',
  WHATSAPP_DEEP_LINK: 'whatsapp://send?text=',
  LINKEDIN_DEEP_LINK: 'otpTimestamps',
  INSTAGRAM_DEEP_LINK: 'instagram://share?text=',
  TWEETER_DEEP_LINK: 'twitter://post?message=',
  SKYPE_DEEP_LINK: 'skype:chat?message=',
  AUTH_GOOGLE: 'USER_GOOGLE',
};
